name: Tunde
favicon: null
layout_spectrum: 0.35621
typography_spectrum: 0.497532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313133'
    - '#d9e5ed'
    - '#6886a6'
    - '#5d606d'
    - '#caa88a'
  brandStrength: 0.679276
  lightness: 0.767269
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
