analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.679276
  lightness: 0.767269
  rhythmicContrast: 0.279605
  saturation: 0.6875
cta: {}
layout_spectrum: 0.320723
name: Tunde
opengraph: {}
purpose: []
typography_spectrum: 0.497532
